// Auto-generated by claude-doc dashboard — do not edit.
// Manage tools via the dashboard's MCP Tools panel.
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import registerWorkflowList from "./tools/workflow-list.js";
import registerWorkflowRun from "./tools/workflow-run.js";
import registerWorkflowStatus from "./tools/workflow-status.js";
import registerWorkflowCancel from "./tools/workflow-cancel.js";

const server = new McpServer({
  name: "claude-doc-tools",
  version: "1.0.0",
});

registerWorkflowList(server);
registerWorkflowRun(server);
registerWorkflowStatus(server);
registerWorkflowCancel(server);

export default server;
