// Auto-generated by vistaclair dashboard — do not edit.
// Manage tools via the dashboard's MCP Tools panel.
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import registerVistaAskUserQuestion from "./tools/vista-ask-user-question.js";

const server = new McpServer({
  name: "vistaclair-tools",
  version: "1.0.0",
});

registerVistaAskUserQuestion(server);

export default server;
