// Auto-generated by clairview — handler body is preserved on regeneration.
import { z } from "zod";

export default function register(server) {
  server.tool(
    "chat",
    "Run a prompt through Claude Code via the dashboard and return the full response. Supports multi-turn via session_id.",
    {
    prompt: z.string().describe("The prompt to send"),
    cwd: z.string().describe("Working directory (inside outputs/)").optional(),
    profile: z.string().describe("Capability profile name").optional(),
    session_id: z.string().describe("Resume a previous session for multi-turn").optional(),
    },
    async (input) => {
  // input is an object with: { prompt, cwd, profile, session_id }
  const { prompt, cwd, profile, session_id } = input;
  const http = await import('http');
  const dashPort = process.env.CLAIRVIEW_DASHBOARD_PORT || '3457';

  const body = JSON.stringify({ type: 'chat', prompt, cwd: cwd || undefined, profile: profile || undefined, sessionId: session_id || undefined });

  return new Promise((resolve) => {
    const timeout = setTimeout(() => resolve({ content: [{ type: 'text', text: 'Timeout waiting for chat response (5 min)' }] }), 300000);
    let text = '', sessionId = null, questions = [];

    const req = http.request({ hostname: '127.0.0.1', port: dashPort, path: '/api/run', method: 'POST', headers: {
      'Content-Type': 'application/json', 'X-Clairview-Internal': 'true', 'Content-Length': Buffer.byteLength(body),
    }}, (res) => {
      let buf = '';
      res.on('data', (chunk) => {
        buf += chunk.toString();
        while (buf.includes('\n\n')) {
          const idx = buf.indexOf('\n\n');
          const block = buf.slice(0, idx); buf = buf.slice(idx + 2);
          let ev = null, data = null;
          for (const line of block.split('\n')) {
            if (line.startsWith('event: ')) ev = line.slice(7);
            else if (line.startsWith('data: ')) data = line.slice(6);
          }
          if (!ev || !data) continue;
          try { data = JSON.parse(data); } catch { continue; }
          if (ev === 'text') text += data.text || '';
          else if (ev === 'ask') questions.push(data);
          else if (ev === 'error') text += '\n[Error: ' + (data.error || 'unknown') + ']\n';
          else if (ev === 'done') {
            clearTimeout(timeout);
            sessionId = data.sessionId || null;
            let result = data.result || text;
            if (sessionId) result += '\n\nsessionId: ' + sessionId;
            if (questions.length > 0) result += '\n\n[Pending questions: ' + JSON.stringify(questions) + ']';
            resolve({ content: [{ type: 'text', text: result }] });
          }
        }
      });
      res.on('end', () => { clearTimeout(timeout); if (text) resolve({ content: [{ type: 'text', text: text + (sessionId ? '\n\nsessionId: ' + sessionId : '') }] }); });
    });
    req.on('error', (e) => { clearTimeout(timeout); resolve({ content: [{ type: 'text', text: 'Error: ' + e.message }] }); });
    req.write(body); req.end();
  });
    }
  );
}
