// Auto-generated by claude-doc — handler body is preserved on regeneration.
import { z } from "zod";

export default function register(server) {
  server.tool(
    "test-tool",
    "this tool sends a greeting back",
    {
    name: z.string().describe("name of the user"),
    },
    async (input) => {
  // input is an object with: { name }
  return {
    content: [{ type: "text", text: `Hello ${input?.name || JSON.stringify(input)}` }],
  };
    }
  );
}
