// Auto-generated by claude-doc — handler body is preserved on regeneration.
import { z } from "zod";

export default function register(server) {
  server.tool(
    "workflow_run",
    "Execute a compiled workflow by name with the given inputs. Returns the run ID. Each step runs a full claude -p session.",
    {
    name: z.string().describe("Name of the workflow to run"),
    inputs: z.record(z.any()).describe("Input values for the workflow (key-value pairs)").optional(),
    },
    async (input) => {
  // input is an object with: { name, inputs }
  const { WebSocket } = await import('ws');
  const dashPort = process.env.CLAUDE_DOC_DASHBOARD_PORT || '3457';
  const token = process.env.CLAUDE_DOC_AUTH_TOKEN || '';
  
  return new Promise((resolve) => {
    const ws = new WebSocket('ws://127.0.0.1:' + dashPort, { headers: { Cookie: 'token=' + token } });
    const timeout = setTimeout(() => { ws.close(); resolve({ content: [{ type: 'text', text: 'Timeout starting workflow' }] }); }, 10000);
    
    ws.on('message', (data) => {
      const msg = JSON.parse(data.toString());
      if (msg.type === 'workflow:run:started') {
        clearTimeout(timeout);
        // Wait for completion
        const runTimeout = setTimeout(() => { ws.close(); resolve({ content: [{ type: 'text', text: 'Run ' + msg.runId + ' started but timed out waiting for completion (still running in background)' }] }); }, 300000);
        ws.on('message', (d2) => {
          const m2 = JSON.parse(d2.toString());
          if (m2.type === 'workflow:run:complete' && m2.runId === msg.runId) {
            clearTimeout(runTimeout);
            ws.close();
            resolve({ content: [{ type: 'text', text: 'Workflow completed. Status: ' + m2.status + ', Run ID: ' + msg.runId }] });
          }
        });
      } else if (msg.type === 'workflow:error') {
        clearTimeout(timeout);
        ws.close();
        resolve({ content: [{ type: 'text', text: 'Error: ' + (msg.error || 'Unknown') }] });
      }
    });
    ws.on('open', () => ws.send(JSON.stringify({ type: 'workflow:run', name, inputs: inputs || {} })));
    ws.on('error', (e) => { clearTimeout(timeout); resolve({ content: [{ type: 'text', text: 'Error: ' + e.message }] }); });
  });
    }
  );
}
