// Auto-generated by clairview — handler body is preserved on regeneration.
import { z } from "zod";

export default function register(server) {
  server.tool(
    "workflow_status",
    "Get the current status of a running workflow, including which step is active and outputs so far",
    {
    run_id: z.string().describe("The run ID returned by workflow_run"),
    },
    async (input) => {
  // input is an object with: { run_id }
  const { run_id } = input;
  const { WebSocket } = await import('ws');
  const dashPort = process.env.CLAIRVIEW_DASHBOARD_PORT || '3457';

  return new Promise((resolve) => {
    const ws = new WebSocket('ws://127.0.0.1:' + dashPort, { headers: { 'X-Clairview-Internal': 'true' } });
    const timeout = setTimeout(() => { ws.close(); resolve({ content: [{ type: 'text', text: 'Timeout getting status' }] }); }, 5000);
    ws.on('message', (data) => {
      const msg = JSON.parse(data.toString());
      if (msg.type === 'workflow:run:status') {
        clearTimeout(timeout);
        ws.close();
        resolve({ content: [{ type: 'text', text: JSON.stringify(msg, null, 2) }] });
      } else if (msg.type === 'workflow:error') {
        clearTimeout(timeout);
        ws.close();
        resolve({ content: [{ type: 'text', text: 'Error: ' + (msg.error || 'Unknown') }] });
      }
    });
    ws.on('open', () => ws.send(JSON.stringify({ type: 'workflow:run:status', runId: run_id })));
    ws.on('error', (e) => { clearTimeout(timeout); resolve({ content: [{ type: 'text', text: 'Error: ' + e.message }] }); });
  });
    }
  );
}
