// Auto-generated by clairview — handler body is preserved on regeneration.
import { z } from "zod";

export default function register(server) {
  server.tool(
    "workflow_run",
    "Execute a compiled workflow by name with the given inputs via the REST API. Returns the final status, run ID, and step outputs.",
    {
    name: z.string().describe("Name of the workflow to run"),
    inputs: z.record(z.any()).describe("Input values for the workflow (key-value pairs)").optional(),
    cwd: z.string().describe("Working directory for the workflow run").optional(),
    },
    async (input) => {
  // input is an object with: { name, inputs, cwd }
  const { name, inputs, cwd } = input;
  const http = await import('http');
  const dashPort = process.env.CLAIRVIEW_DASHBOARD_PORT || '3457';

  const body = JSON.stringify({ type: 'workflow', workflow: name, inputs: inputs || {}, cwd: cwd || undefined });

  return new Promise((resolve) => {
    const timeout = setTimeout(() => resolve({ content: [{ type: 'text', text: 'Timeout waiting for workflow completion (5 min)' }] }), 300000);
    let text = '', steps = [], questions = [];

    const req = http.request({ hostname: '127.0.0.1', port: dashPort, path: '/api/run', method: 'POST', headers: {
      'Content-Type': 'application/json', 'X-Clairview-Internal': 'true', 'Content-Length': Buffer.byteLength(body),
    }}, (res) => {
      let buf = '';
      res.on('data', (chunk) => {
        buf += chunk.toString();
        while (buf.includes('\n\n')) {
          const idx = buf.indexOf('\n\n');
          const block = buf.slice(0, idx); buf = buf.slice(idx + 2);
          let ev = null, data = null;
          for (const line of block.split('\n')) {
            if (line.startsWith('event: ')) ev = line.slice(7);
            else if (line.startsWith('data: ')) data = line.slice(6);
          }
          if (!ev || !data) continue;
          try { data = JSON.parse(data); } catch { continue; }
          if (ev === 'text') text += data.text || '';
          else if (ev === 'step') steps.push(data);
          else if (ev === 'ask') questions.push(data);
          else if (ev === 'error') text += '\n[Error: ' + (data.error || 'unknown') + ']\n';
          else if (ev === 'done') {
            clearTimeout(timeout);
            let result = 'Status: ' + (data.result || 'unknown');
            if (data.runId) result += '\nRun ID: ' + data.runId;
            if (steps.length > 0) result += '\n\nSteps:\n' + steps.map(s => '  ' + s.stepId + ': ' + (s.status || s.text || '')).join('\n');
            if (text) result += '\n\nOutput:\n' + text;
            if (questions.length > 0) result += '\n\n[Pending questions: ' + JSON.stringify(questions) + ']';
            resolve({ content: [{ type: 'text', text: result }] });
          }
        }
      });
      res.on('end', () => { clearTimeout(timeout); resolve({ content: [{ type: 'text', text: text || 'Workflow stream ended without completion event' }] }); });
    });
    req.on('error', (e) => { clearTimeout(timeout); resolve({ content: [{ type: 'text', text: 'Error: ' + e.message }] }); });
    req.write(body); req.end();
  });
    }
  );
}
