// Auto-generated by clairview — handler body is preserved on regeneration.
import { z } from "zod";

export default function register(server) {
  server.tool(
    "workflow_list",
    "List all available workflows with their status (draft, compiled, needs-compile)",
    {

    },
    async (input) => {
  // input is an object with: {  }
  const http = await import('http');
  const { WebSocket } = await import('ws');
  const dashPort = process.env.CLAIRVIEW_DASHBOARD_PORT || '3457';
  const internalHeaders = { 'X-Clairview-Internal': 'true' };

  return new Promise((resolve) => {
    // Use WebSocket to query
    const ws = new WebSocket('ws://127.0.0.1:' + dashPort, { headers: internalHeaders });
    const timeout = setTimeout(() => { ws.close(); resolve({ content: [{ type: 'text', text: 'Timeout waiting for workflow list' }] }); }, 5000);
    ws.on('message', (data) => {
      const msg = JSON.parse(data.toString());
      if (msg.type === 'workflow:list') {
        clearTimeout(timeout);
        ws.close();
        resolve({ content: [{ type: 'text', text: JSON.stringify(msg.workflows, null, 2) }] });
      }
    });
    ws.on('open', () => ws.send(JSON.stringify({ type: 'workflow:list' })));
    ws.on('error', (e) => { clearTimeout(timeout); resolve({ content: [{ type: 'text', text: 'Error: ' + e.message }] }); });
  });
    }
  );
}
