// Auto-generated by claude-doc — handler body is preserved on regeneration.
import { z } from "zod";

export default function register(server) {
  server.tool(
    "workflow_list",
    "List all available workflows with their status (draft, compiled, needs-compile)",
    {

    },
    async (input) => {
  // input is an object with: {  }
  const http = await import('http');
  const dashPort = process.env.CLAUDE_DOC_DASHBOARD_PORT || '3457';
  const token = process.env.CLAUDE_DOC_AUTH_TOKEN || '';
  
  return new Promise((resolve) => {
    const req = http.request({
      hostname: '127.0.0.1', port: dashPort, path: '/login',
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded', 'Cookie': 'token=' + token }
    }, () => {});
    req.end();
    
    // Use WebSocket to query
    const { WebSocket } = await import('ws');
    const ws = new WebSocket('ws://127.0.0.1:' + dashPort, { headers: { Cookie: 'token=' + token } });
    const timeout = setTimeout(() => { ws.close(); resolve({ content: [{ type: 'text', text: 'Timeout waiting for workflow list' }] }); }, 5000);
    ws.on('message', (data) => {
      const msg = JSON.parse(data.toString());
      if (msg.type === 'workflow:list') {
        clearTimeout(timeout);
        ws.close();
        resolve({ content: [{ type: 'text', text: JSON.stringify(msg.workflows, null, 2) }] });
      }
    });
    ws.on('open', () => ws.send(JSON.stringify({ type: 'workflow:list' })));
    ws.on('error', (e) => { clearTimeout(timeout); resolve({ content: [{ type: 'text', text: 'Error: ' + e.message }] }); });
  });
    }
  );
}
