// Auto-generated by claude-doc — handler body is preserved on regeneration.
import { z } from "zod";

export default function register(server) {
  server.tool(
    "workflow_cancel",
    "Cancel a running workflow",
    {
    run_id: z.string().describe("The run ID to cancel"),
    },
    async (input) => {
  // input is an object with: { run_id }
  const { run_id } = input;
  const { WebSocket } = await import('ws');
  const dashPort = process.env.CLAUDE_DOC_DASHBOARD_PORT || '3457';
  const token = process.env.CLAUDE_DOC_AUTH_TOKEN || '';
  
  return new Promise((resolve) => {
    const ws = new WebSocket('ws://127.0.0.1:' + dashPort, { headers: { Cookie: 'token=' + token } });
    const timeout = setTimeout(() => { ws.close(); resolve({ content: [{ type: 'text', text: 'Cancel sent' }] }); }, 3000);
    ws.on('open', () => {
      ws.send(JSON.stringify({ type: 'workflow:run:cancel', runId: run_id }));
      clearTimeout(timeout);
      setTimeout(() => { ws.close(); resolve({ content: [{ type: 'text', text: 'Cancel request sent for run ' + run_id }] }); }, 500);
    });
    ws.on('error', (e) => { clearTimeout(timeout); resolve({ content: [{ type: 'text', text: 'Error: ' + e.message }] }); });
  });
    }
  );
}
